# Copyright (C) 2017-2019 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/dreamlte/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/dreamlte/proprietary/lib/hw/camera.universal8895.so:system/lib/hw/camera.universal8895.so \
    vendor/samsung/dreamlte/proprietary/lib/libFacePreProcessing.camera.samsung.so:system/lib/libFacePreProcessing.camera.samsung.so \
    vendor/samsung/dreamlte/proprietary/lib/libFacePreProcessing_jni.camera.samsung.so:system/lib/libFacePreProcessing_jni.camera.samsung.so \
    vendor/samsung/dreamlte/proprietary/lib/libFacialBasedSelfieCorrection.camera.samsung.so:system/lib/libFacialBasedSelfieCorrection.camera.samsung.so \
    vendor/samsung/dreamlte/proprietary/lib/libIDDQD_core.so:system/lib/libIDDQD_core.so \
    vendor/samsung/dreamlte/proprietary/lib/libIDDQD_interface.so:system/lib/libIDDQD_interface.so \
    vendor/samsung/dreamlte/proprietary/lib/libblurdetection.so:system/lib/libblurdetection.so \
    vendor/samsung/dreamlte/proprietary/lib/libblurdetection_interface.so:system/lib/libblurdetection_interface.so \
    vendor/samsung/dreamlte/proprietary/lib/libexynoscamera.so:system/lib/libexynoscamera.so \
    vendor/samsung/dreamlte/proprietary/lib/libexynoscamera3.so:system/lib/libexynoscamera3.so \
    vendor/samsung/dreamlte/proprietary/lib/libfocuspeaking.so:system/lib/libfocuspeaking.so \
    vendor/samsung/dreamlte/proprietary/lib/libfocuspeaking_interface.so:system/lib/libfocuspeaking_interface.so \
    vendor/samsung/dreamlte/proprietary/lib/libhifills_interface.so:system/lib/libhifills_interface.so \
    vendor/samsung/dreamlte/proprietary/lib/libhwjpeg.so:system/lib/libhwjpeg.so \
    vendor/samsung/dreamlte/proprietary/lib/libsensorlistener.so:system/lib/libsensorlistener.so \
    vendor/samsung/dreamlte/proprietary/lib/libsmartfocus_interface.so:system/lib/libsmartfocus_interface.so \
    vendor/samsung/dreamlte/proprietary/lib/libsmartfocusengine.so:system/lib/libsmartfocusengine.so \
    vendor/samsung/dreamlte/proprietary/lib/libuniapi.so:system/lib/libuniapi.so \
    vendor/samsung/dreamlte/proprietary/lib/libuniplugin.so:system/lib/libuniplugin.so \
    vendor/samsung/dreamlte/proprietary/lib64/hw/camera.universal8895.so:system/lib64/hw/camera.universal8895.so \
    vendor/samsung/dreamlte/proprietary/lib64/libIDDQD_core.so:system/lib64/libIDDQD_core.so \
    vendor/samsung/dreamlte/proprietary/lib64/libIDDQD_interface.so:system/lib64/libIDDQD_interface.so \
    vendor/samsung/dreamlte/proprietary/lib64/libblurdetection.so:system/lib64/libblurdetection.so \
    vendor/samsung/dreamlte/proprietary/lib64/libblurdetection_interface.so:system/lib64/libblurdetection_interface.so \
    vendor/samsung/dreamlte/proprietary/lib64/libexynoscamera.so:system/lib64/libexynoscamera.so \
    vendor/samsung/dreamlte/proprietary/lib64/libexynoscamera3.so:system/lib64/libexynoscamera3.so \
    vendor/samsung/dreamlte/proprietary/lib64/libfocuspeaking.so:system/lib64/libfocuspeaking.so \
    vendor/samsung/dreamlte/proprietary/lib64/libfocuspeaking_interface.so:system/lib64/libfocuspeaking_interface.so \
    vendor/samsung/dreamlte/proprietary/lib64/libhifills_interface.so:system/lib64/libhifills_interface.so \
    vendor/samsung/dreamlte/proprietary/lib64/libhwjpeg.so:system/lib64/libhwjpeg.so \
    vendor/samsung/dreamlte/proprietary/lib64/libsensorlistener.so:system/lib64/libsensorlistener.so \
    vendor/samsung/dreamlte/proprietary/lib64/libsmartfocus_interface.so:system/lib64/libsmartfocus_interface.so \
    vendor/samsung/dreamlte/proprietary/lib64/libsmartfocusengine.so:system/lib64/libsmartfocusengine.so \
    vendor/samsung/dreamlte/proprietary/lib64/libuniapi.so:system/lib64/libuniapi.so \
    vendor/samsung/dreamlte/proprietary/lib64/libuniplugin.so:system/lib64/libuniplugin.so \
    vendor/samsung/dreamlte/proprietary/vendor/etc/plmn_delta.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta.bin \
    vendor/samsung/dreamlte/proprietary/vendor/etc/plmn_delta_attaio.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta_attaio.bin \
    vendor/samsung/dreamlte/proprietary/vendor/etc/plmn_delta_usacdma.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta_usacdma.bin \
    vendor/samsung/dreamlte/proprietary/vendor/etc/plmn_delta_usagsm.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta_usagsm.bin \
    vendor/samsung/dreamlte/proprietary/vendor/etc/plmn_se13.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_se13.bin \
    vendor/samsung/dreamlte/proprietary/vendor/etc/snap_gpu_kernel_32.bin:$(TARGET_COPY_OUT_VENDOR)/etc/snap_gpu_kernel_32.bin \
    vendor/samsung/dreamlte/proprietary/vendor/etc/snap_gpu_kernel_64.bin:$(TARGET_COPY_OUT_VENDOR)/etc/snap_gpu_kernel_64.bin \
    vendor/samsung/dreamlte/proprietary/vendor/firmware/APBargeIn_AUDIO_SLSI.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/APBargeIn_AUDIO_SLSI.bin \
    vendor/samsung/dreamlte/proprietary/vendor/firmware/APBiBF_AUDIO_SLSI.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/APBiBF_AUDIO_SLSI.bin \
    vendor/samsung/dreamlte/proprietary/vendor/firmware/AP_AUDIO_SLSI.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/AP_AUDIO_SLSI.bin \
    vendor/samsung/dreamlte/proprietary/vendor/firmware/SoundBoosterParam.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/SoundBoosterParam.bin \
    vendor/samsung/dreamlte/proprietary/vendor/firmware/bcm4361B0_murata.hcd:$(TARGET_COPY_OUT_VENDOR)/firmware/bcm4361B0_murata.hcd \
    vendor/samsung/dreamlte/proprietary/vendor/firmware/bcm4361B0_semco.hcd:$(TARGET_COPY_OUT_VENDOR)/firmware/bcm4361B0_semco.hcd \
    vendor/samsung/dreamlte/proprietary/vendor/firmware/calliope_dram.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/calliope_dram.bin \
    vendor/samsung/dreamlte/proprietary/vendor/firmware/calliope_iva.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/calliope_iva.bin \
    vendor/samsung/dreamlte/proprietary/vendor/firmware/calliope_sram.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/calliope_sram.bin \
    vendor/samsung/dreamlte/proprietary/vendor/firmware/companion_2l2_master_setfile.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/companion_2l2_master_setfile.bin \
    vendor/samsung/dreamlte/proprietary/vendor/firmware/companion_2l2_mode_setfile.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/companion_2l2_mode_setfile.bin \
    vendor/samsung/dreamlte/proprietary/vendor/firmware/companion_fw_2l2_3h1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/companion_fw_2l2_3h1.bin \
    vendor/samsung/dreamlte/proprietary/vendor/firmware/companion_fw_2l2_imx320.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/companion_fw_2l2_imx320.bin \
    vendor/samsung/dreamlte/proprietary/vendor/firmware/companion_fw_imx333_3h1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/companion_fw_imx333_3h1.bin \
    vendor/samsung/dreamlte/proprietary/vendor/firmware/companion_fw_imx333_imx320.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/companion_fw_imx333_imx320.bin \
    vendor/samsung/dreamlte/proprietary/vendor/firmware/companion_imx333_master_setfile.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/companion_imx333_master_setfile.bin \
    vendor/samsung/dreamlte/proprietary/vendor/firmware/companion_imx333_mode_setfile.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/companion_imx333_mode_setfile.bin \
    vendor/samsung/dreamlte/proprietary/vendor/firmware/dsm.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dsm.bin \
    vendor/samsung/dreamlte/proprietary/vendor/firmware/dsm_tune.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dsm_tune.bin \
    vendor/samsung/dreamlte/proprietary/vendor/firmware/fimc_is_lib.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/fimc_is_lib.bin \
    vendor/samsung/dreamlte/proprietary/vendor/firmware/fimc_is_rta_2l2_3h1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/fimc_is_rta_2l2_3h1.bin \
    vendor/samsung/dreamlte/proprietary/vendor/firmware/fimc_is_rta_2l2_imx320.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/fimc_is_rta_2l2_imx320.bin \
    vendor/samsung/dreamlte/proprietary/vendor/firmware/fimc_is_rta_imx333_3h1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/fimc_is_rta_imx333_3h1.bin \
    vendor/samsung/dreamlte/proprietary/vendor/firmware/fimc_is_rta_imx333_imx320.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/fimc_is_rta_imx333_imx320.bin \
    vendor/samsung/dreamlte/proprietary/vendor/firmware/iva10_rt-kangchen.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/iva10_rt-kangchen.bin \
    vendor/samsung/dreamlte/proprietary/vendor/firmware/mfc_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mfc_fw.bin \
    vendor/samsung/dreamlte/proprietary/vendor/firmware/nfc/sec_s3nrn82_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nfc/sec_s3nrn82_firmware.bin \
    vendor/samsung/dreamlte/proprietary/vendor/firmware/ois_fw_dom.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/ois_fw_dom.bin \
    vendor/samsung/dreamlte/proprietary/vendor/firmware/ois_fw_sec.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/ois_fw_sec.bin \
    vendor/samsung/dreamlte/proprietary/vendor/firmware/score_fw_dmb0.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/score_fw_dmb0.bin \
    vendor/samsung/dreamlte/proprietary/vendor/firmware/score_fw_dmb1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/score_fw_dmb1.bin \
    vendor/samsung/dreamlte/proprietary/vendor/firmware/score_fw_pmw0.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/score_fw_pmw0.bin \
    vendor/samsung/dreamlte/proprietary/vendor/firmware/score_fw_pmw1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/score_fw_pmw1.bin \
    vendor/samsung/dreamlte/proprietary/vendor/firmware/setfile_2l2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile_2l2.bin \
    vendor/samsung/dreamlte/proprietary/vendor/firmware/setfile_3h1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile_3h1.bin \
    vendor/samsung/dreamlte/proprietary/vendor/firmware/setfile_imx320.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile_imx320.bin \
    vendor/samsung/dreamlte/proprietary/vendor/firmware/setfile_imx333.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile_imx333.bin \
    vendor/samsung/dreamlte/proprietary/vendor/firmware/vts.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/vts.bin \
    vendor/samsung/dreamlte/proprietary/vendor/lib/libDLInterface.camera.samsung.so:$(TARGET_COPY_OUT_VENDOR)/lib/libDLInterface.camera.samsung.so \
    vendor/samsung/dreamlte/proprietary/vendor/lib/libOpenCv.camera.samsung.so:$(TARGET_COPY_OUT_VENDOR)/lib/libOpenCv.camera.samsung.so \
    vendor/samsung/dreamlte/proprietary/vendor/lib/libhifistill.so:$(TARGET_COPY_OUT_VENDOR)/lib/libhifistill.so \
    vendor/samsung/dreamlte/proprietary/vendor/lib/libhifistill_tuning.so:$(TARGET_COPY_OUT_VENDOR)/lib/libhifistill_tuning.so \
    vendor/samsung/dreamlte/proprietary/vendor/lib/libhumantracking_util.camera.samsung.so:$(TARGET_COPY_OUT_VENDOR)/lib/libhumantracking_util.camera.samsung.so \
    vendor/samsung/dreamlte/proprietary/vendor/lib/libiva_android_hal.so:$(TARGET_COPY_OUT_VENDOR)/lib/libiva_android_hal.so \
    vendor/samsung/dreamlte/proprietary/vendor/lib/libopenvx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libopenvx.so \
    vendor/samsung/dreamlte/proprietary/vendor/lib/libsmart_cropping.camera.samsung.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsmart_cropping.camera.samsung.so \
    vendor/samsung/dreamlte/proprietary/vendor/lib/libsnap_caffe.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsnap_caffe.so \
    vendor/samsung/dreamlte/proprietary/vendor/lib/libsnap_caffe_wrapper.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsnap_caffe_wrapper.so \
    vendor/samsung/dreamlte/proprietary/vendor/lib/libsnap_compute.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsnap_compute.so \
    vendor/samsung/dreamlte/proprietary/vendor/lib/libsnap_compute_wrapper.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsnap_compute_wrapper.so \
    vendor/samsung/dreamlte/proprietary/vendor/lib/libsnap_vndk.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsnap_vndk.so \
    vendor/samsung/dreamlte/proprietary/vendor/lib/libsomp.camera.samsung.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsomp.camera.samsung.so \
    vendor/samsung/dreamlte/proprietary/vendor/lib/libvxu.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvxu.so \
    vendor/samsung/dreamlte/proprietary/vendor/lib/libxcv.camera.samsung.so:$(TARGET_COPY_OUT_VENDOR)/lib/libxcv.camera.samsung.so \
    vendor/samsung/dreamlte/proprietary/vendor/lib64/libDLInterface.camera.samsung.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libDLInterface.camera.samsung.so \
    vendor/samsung/dreamlte/proprietary/vendor/lib64/libOpenCv.camera.samsung.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libOpenCv.camera.samsung.so \
    vendor/samsung/dreamlte/proprietary/vendor/lib64/libhifistill.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libhifistill.so \
    vendor/samsung/dreamlte/proprietary/vendor/lib64/libhifistill_tuning.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libhifistill_tuning.so \
    vendor/samsung/dreamlte/proprietary/vendor/lib64/libhumantracking_util.camera.samsung.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libhumantracking_util.camera.samsung.so \
    vendor/samsung/dreamlte/proprietary/vendor/lib64/libiva_android_hal.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libiva_android_hal.so \
    vendor/samsung/dreamlte/proprietary/vendor/lib64/libopenvx.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libopenvx.so \
    vendor/samsung/dreamlte/proprietary/vendor/lib64/libsmart_cropping.camera.samsung.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsmart_cropping.camera.samsung.so \
    vendor/samsung/dreamlte/proprietary/vendor/lib64/libsnap_caffe.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsnap_caffe.so \
    vendor/samsung/dreamlte/proprietary/vendor/lib64/libsnap_caffe_wrapper.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsnap_caffe_wrapper.so \
    vendor/samsung/dreamlte/proprietary/vendor/lib64/libsnap_compute.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsnap_compute.so \
    vendor/samsung/dreamlte/proprietary/vendor/lib64/libsnap_compute_wrapper.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsnap_compute_wrapper.so \
    vendor/samsung/dreamlte/proprietary/vendor/lib64/libsnap_vndk.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsnap_vndk.so \
    vendor/samsung/dreamlte/proprietary/vendor/lib64/libsomp.camera.samsung.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsomp.camera.samsung.so \
    vendor/samsung/dreamlte/proprietary/vendor/lib64/libvxu.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libvxu.so \
    vendor/samsung/dreamlte/proprietary/vendor/lib64/libxcv.camera.samsung.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libxcv.camera.samsung.so
